services:
  - type: web
    name: augustus-ai-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MISTRAL_API_KEY
        sync: false 